[package]
name = "example_rubiks_cube"
version = "0.1.0"
edition = "2024"

[dependencies]
meet_in_the_middle = { path = "../meet_in_the_middle" }
indenter = { version = "0.2"}
rand = "0.9.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "solve_cube"
harness = false